### PR TITLE
3415 feature skill self evaluation search and sort

### LINKED ISSUE #3415: [FEATURE] Skill Self Evaluation occupation search and sort
**Is your feature request related to a problem? Please describe.**
Currently we just see one long list of all occupations but we would like to be able to see the best and worst matches by changing the sort order and find a secific job by searching.

**Describe the solution you'd like**
We should add a search bar and a sort direction button that filters the results on the front end based on the provided search query and sorts the results by score either ascending or descending based on the sort button selection. The search should be done on the front end since there are not that many occupations and should support fuzzy/partial matches if possible (maybe use RegEx?).

### PR DESCRIPTION
**Pull request by akshadpai**
## Description
Search the best and worst matches for the career explorer by changing the sort order and find a specific job by searching through names using regex.

**Fixes #3415 **

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by akshadpai** [comment]
There is a constraint issue on the career explorer panel. Currently there is a container with a fixed height holding a list view of the occupations.

**Review by mihail-varbanov — CHANGES_REQUESTED** [review]
1. There is an exception when the Career Explorer panel gets loaded:

```
[ +295 ms] flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[        ] flutter: The following assertion was thrown during layout:
[        ] flutter: A RenderFlex overflowed by 87 pixels on the bottom.
[        ] flutter:
[        ] flutter: The relevant error-causing widget was:
[        ] flutter:   Column
[        ] flutter:
[        ] flutter:
[        ] flutter: To inspect this widget in Flutter DevTools, visit:
[        ] flutter: http://127.0.0.1:9100/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A50208%2FanqhOwhrt7Q%3D%2F&inspectorRef=inspector-0
[        ] flutter:
[        ] flutter: The overflowing RenderFlex has an orientation of Axis.vertical.
[        ] flutter: The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
[   +6 ms] flutter: black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
[        ] flutter: Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
[        ] flutter: RenderFlex to fit within the available space instead of being sized to their natural size.
[        ] flutter: This is considered an error condition because it indicates that there is content that cannot be
[        ] flutter: seen. If the content is legitimately bigger than the available space, consider clipping it with a
[        ] flutter: ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
[        ] flutter: like a ListView.
[        ] flutter: The specific RenderFlex in question is: RenderFlex#8ac50 relayoutBoundary=up1 OVERFLOWING:
[        ] flutter:   needs compositing
[        ] flutter:   creator: Column ← SectionSlantHeader ← KeyedSubtree-[GlobalKey#13f64] ← _BodyBuilder ← MediaQuery ←
[        ] flutter:     LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← _ActionsScope ← Actions ←
[        ] flutter:     AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← ⋯
[        ] flutter:   parentData: offset=Offset(0.0, 103.0); id=_ScaffoldSlot.body (can use size)
[        ] flutter:   constraints: BoxConstraints(0.0<=w<=390.0, 0.0<=h<=529.2)
[        ] flutter:   size: Size(390.0, 529.2)
[        ] flutter:   direction: vertical
[        ] flutter:   mainAxisAlignment: start
[        ] flutter:   mainAxisSize: max
[        ] flutter:   crossAxisAlignment: center
[        ] flutter:   verticalDirection: down
[        ] flutter: ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 87 pixels on the bottom.

The relevant error-causing widget was
Column
To inspect this widget in Flutter DevTools, visit: http://127.0.0.1:9100/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A50208%2FanqhOwhrt7Q%3D%2F&inspectorRef=inspector-0
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#8ac50 relayoutBoundary=up1 OVERFLOWING
════════════════════════════════════════════════════════════════════════════════
```
Screen Shot 2023-07-18 at 8 37 41 AM

2. If we hide the keyboard the list content does not expand the available space vertically:

Screen Shot 2023-07-18 at 8 40 37 AM

**Comment by mihail-varbanov** [comment]
> There is a constraint issue on the career explorer panel. Currently there is a container with a fixed height holding a list view of the occupations.

SectionSlantHeader is not suitable in this case. Normally it is placed inside a SingleChildScrollView and OccupationListTile widgets are supplied as its children. I would try a structure like this:

```
Column(children:[
  <Blue Header: Title, Text Field, etc.>,
  Expanded(child:
    Stack(children:[
      TrianglePainter(),
      ListView()
    ])
  )
])
```

**Comment by shurwit** [comment]
Hi @mihail-varbanov, thanks for taking a look at this and for the suggestions! As a reminder you are welcome to leave PRs from my team for me to review first if you have other priorities, but I really appreicate your feedback! We will make some changes and let you know when it is ready for another review.

**Comment by mihail-varbanov** [comment]
Thank you for your feedback, @shurwit! Yes, it would be way better if you make some internal review first. I looked at this PR because it was assigned to me as a reviewer and I thought that you were expecting me to review and merge it. Let's determine who should look at a PR by its assignee and reviewer. I will look at a PR only if I am involved as an assignee or reviewer, so your team should just take care who of us is expected to process it.

**Comment by shurwit** [comment]
> Thank you for your feedback, @shurwit! Yes, it would be way better if you make some internal review first. I looked at this PR because it was assigned to me as a reviewer and I thought that you were expecting me to review and merge it. Let's determine who should look at a PR by its assignee and reviewer. I will look at a PR only if I am involved as an assignee or reviewer, so your team should just take care who of us is expected to process it.
> 

Hi @mihail-varbanov, yes sorry about that! I believe you will always be automatically assigned as a reviewer since you are the code owner of this repo. We are not able to unassign you when we open PRs. This may be a configuration that we could change, but I don't think we want to because I believe that would allow anyone to review and merge a PR without you taking a look. Let me know if you have any thoughts on how best to indicate when the PRs are ready for you with this in mind. Thanks again!

**Comment by mihail-varbanov** [comment]
No problems at all, @shurwit. What about adding an elicit notice (comment) when you expect me to process some PR, e.g. "@mihail-varbanov, please review and merge this."?

**Comment by shurwit** [comment]
Hi @mihail-varbanov, thanks again for the suggestion. I have made the change and I believe this is now ready to be merged when you get a chance. Thanks!

**Review by shurwit — APPROVED** [review]
Thanks @akshadpai, LGTM!

**Comment by mihail-varbanov** [comment]
Thanks @shurwit! All looks good to me either. I just made some small cosmetic changes and merged the branch.

**Pull request merged**
