### PR TITLE
4290/search buildings

### LINKED ISSUE #4290: [FEATURE] Text search for campus buildings
Users would like to be able to search for a building by typing a name or keyword. This feature will exist as a button map when Campus Buildings is selected.

### PR DESCRIPTION
**Pull request by aidanhenry**
## Description
This adds the search feature which was accidentally missing from previous PR. I have done my best to avoid running in to the same issues that the previous PR had. This was feature was based on the existing event search feature, but simplified. I do not see any new errors.

**Fixes #4290 **

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [ ] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by aidanhenry** [comment]
It looks like I'm many commits ahead of the support branch. What's the best way to get this synced up?

**Comment by mihail-varbanov** [comment]
Just merge the current content of [support/v6.0](https://github.com/rokwire/illinois-app/tree/support/v6.0) branch to your [4290/search-buildings](https://github.com/aidanhenry/illinois-app/tree/4290/search-buildings) branch before creating the PR.

**Comment by mihail-varbanov** [comment]
Did you create [4290/search-buildings](https://github.com/aidanhenry/illinois-app/tree/4290/search-buildings) branch as  a fork from [develop](https://github.com/rokwire/illinois-app/tree/develop) branch? If yes, this was wrong and you have to create a brand new branch from current [support/v6.0](https://github.com/rokwire/illinois-app/tree/support/v6.0), and then add your updates related to #4290.

**Comment by aidanhenry** [comment]
Closing this PR to reopen it from a branch forked from support/v6.0

**Pull request closed without merging**
