### PR TITLE
[#2668] Standardize logged out widget

### LINKED ISSUE #2658: [BUG] MyMcKinley Appointments message for Privacy level 3 or lower
**Describe the bug**
For a user with Privacy level 3 or lower, no message says they should be logged in to use the feature.

**To Reproduce**
1. Use app with Level 3 or lower
2. Go to Wellness > MyMcKinley Appointments

**Expected behavior**
A message saying, "You need to be signed in with your NetID to access MyMcKinley Appointments. Set your privacy level to 4 or 5 in your Profile. Then find the sign-in prompt under Settings."

### LINKED ISSUE #2668: [FEATURE] Standardize logged out widget
**Is your feature request related to a problem? Please describe.**
There is no standard widget to show a certain privacy level or login type is required to access a given feature of the app.

**Describe the solution you'd like**
Create a widget that can be shown to users when they are logged out or their privacy level is too low, not allowing access to a given feature of the app. The widget should accept arguments such as minimum privacy level and any required login type, and it should have action buttons that open the relevant content in Settings or Profile to be able to login or update privacy level.

**Describe alternatives you've considered**
A standard widget is unnecessary, but it will be helpful in keeping styling consistent and cut down on code duplication on each panel that needs to use similar functionality.

### PR DESCRIPTION
**Pull request by roberlander2**
## Description
This PR defines `FlexUI`-based widgets that indicate to users why they may be unable to access certain features of the app (e.g., the Illinois Health Screener, MyMcKinley appointments, etc.) and which steps they need to follow to gain access to those features. Depends on https://github.com/rokwire/app-flutter-plugin/pull/233.

**Fixes #2668**
**Fixes #2658**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Review by mihail-varbanov — CHANGES_REQUESTED** [review]
Hi @roberlander2, can you think of some simpler solution instead of FlexUI.unsatisfiedRulesForEntry. For example, what about if you define entries in "features" section like "may_access_role_available",  "may_access_privacy_available", "may_access_auth_available", add the relevant rules for these entries, then test if the feature is available or not using FlexUI().hasFeature, and construct the relevant _AccessContent content? FlexUI.unsatisfiedRulesForEntry is just too heavy and complex and I do not want to keep it in FlexUI for so specific need like this in _AccessContent.

**Comment by roberlander2** [comment]
Thanks @mihail-varbanov,
I implemented a solution similar to what you suggested. I replaced "may_access" with "roles_access", "privacy_access", and "auth_access" and use the `FlexUI` service to remove these feature strings from each entry in `content` according to the rules. I removed `unsatisfiedRulesForEntry` from https://github.com/rokwire/app-flutter-plugin/pull/233, and added a getter for the default rules map to be used by `_AccessContent`. Please let me know if you see issues with the new implementation.

**Review by mihail-varbanov — APPROVED** [review]
Hi @roberlander2,

Great, I do not know for you but it looks much simpler and better to me.

I just did a cosmetic update in flex UI content.

1. Normally, in an entry like "wellness.health_screener" we would expect to see some codes that define the content structure of WellnessHealthScreenerHomeWidget. We place codes like your access codes in the "features" list, that are not supposed to define the content and structure of some panel or widget but rather to define whether given features persist or not. We already have the common "features" list as well as the "campus_guide.features". That's why I renamed your entries that hold the "access" codes to contain ".features" suffix in their names.

2. Having simply the "privacy_access" rule inside the privacy rules is too common. It just sounds too common and can vary in different contexts. That's why I replaced the "privacy_access" rule with 3 uniform rule entries for the three different contexts where this code is defined.

**Comment by roberlander2** [comment]
Thanks @mihail-varbanov,

I think the changes you made to `flexUI.json` will be fine. I did more testing, and they only appear to have broken some of the strings, which I fixed here (along with another bug fix related to the Skills Self-Evaluation): https://github.com/rokwire/illinois-app/pull/2772.

**Comment by mihail-varbanov** [comment]
Thank you, @roberlander2!

**Pull request merged**
