### PR TITLE
[#2777] Polls :: not-signed-in error - needs better message

### LINKED ISSUE #2777: [USABILITY] Polls :: not-signed-in error - needs better message
When a user is not signed in with NetID, they cannot view Polls.

The error message for this condition is not user friendly.

> "Server Response Error: 401 Unauthorized"

I suggest adding a proper "not logged in" message such was what @roberlander2 is working on.

IMG_1775 2 copy

### LINKED ISSUE #2827: [BUG] Privacy level3 - View poll results Server response error
**Describe the bug**
"Server Response Error:401 Unauthorized" is displayed when a user with Privacy level 3, taps on the View poll

**To Reproduce**
1. Install Illinois app
2. User with Privacy level 3
3. Navigate to Browser -> POll and tap on View poll

**Actual Result**
"Server Response Error:401 Unauthorized" is displayed when a user with Privacy level 3, taps on the View poll

**Screenshots**
poll er

**Smartphone (please complete the following information):**
 - Device: [e.g. android]
 - Version [e.g. 4.2.45]

### PR DESCRIPTION
**Pull request by roberlander2**
## Description
This PR adds the `AccessCard` to the `PollsHomePanel` and uses the `AccessDialog` in `CreatePollsPanel.present` to control access based on `FlexUI` content.

**Fixes #2777**
**Fixes #2827**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by mihail-varbanov** [comment]
@roberlander2, I will not approve and merge this now because we are just before a release.

I see where you are going. What I am wondering is that instead of creating a large number of identical rules in FlexUI (currently for skills_self_evaluation, appointments and polls), why don't we try to define a single rule and reuse it, e.g:
```
"oidc_loggedin.features": ["roles_access", "privacy_access", "auth_access"]
"oidc_loggedin.student.features": ["roles_access", "privacy_access", "auth_access"]

"oidc_loggedin.student.features.roles_access" : ["student"]

"oidc_loggedin.features.privacy_access" : 4,
"oidc_loggedin.features,student.privacy_access" : 4,

"oidc_loggedin.features.auth_access" : { "shibbolethLoggedIn": true },
"oidc_loggedin.features,student.auth_access" : { "shibbolethLoggedIn": true },
```
Or maybe something even more clever that would not require duplication of the general and student's privacy and auth access rules?I know that you rely on the current rules separation to access proper string resource entries, but this could be resolved by passing an additional parameter to Access widgets constructors. What do you think? Would this be for better or not?

**Comment by roberlander2** [comment]
Thanks @mihail-varbanov,

I agree that we should avoid writing a lot of very similar FlexUI rules. I'm not sure if the solution you suggested will allow us to easily change access to UI in the JSON because I am not sure what the `<resource>.features` list should look like. I will think about this some more to find a solution to limit the number of similar rules we need to write.

**Comment by mihail-varbanov** [comment]
Thanks for your comment, @roberlander2! I did not quite understand what you mean by "change access to UI in the JSON" but my feeling is that we would better keep the way that you have currently taken, for now. When the access rules get huge enough we will have a better view of how they can be optimized, what the exceptions are, etc. And we can merge the identical rules at any time, including at the end of switching to use the new Access controls.

**Comment by roberlander2** [comment]
Hi @mihail-varbanov, I did a refactor of the access widgets and `flex_ui.json` to use the `features` list. Basically, the new implementation specifies features required to access a resource in the `<resource>.features` list, and we can simply specify `features` rules as we already have done in the `privacy` section. I think this implementation does a good job with avoiding the need to write very similar rules for each resource, as you suggested. Please let me know if you have any questions about these changes or any more comments. Thanks!

**Review by mihail-varbanov — APPROVED** [review]
Hi @roberlander2, it looks perfect to me now! You have found a very good solution using the existing "features" list, that is generally its purpose. I am not only approving this PR but also merging it because as far as I see the management of this project is far away from freezing the code before the release.

**Pull request merged**
