### PR TITLE
[FEATURE] Filter pins on map to match filters/search for storied sites 

### LINKED ISSUE #4458: [FEATURE] Filter pins on map to match filters/search for storied sites
**Is your feature request related to a problem? Please describe.**
Filter pins on map to match filters/search for storied sites

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by manav2modi**
## Description
_Please provide a summary of the pull request and the issue it fixes. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

**Fixes #4458**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [ ] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by manav2modi** [comment]
@mihail-varbanov I have also added the feature so that when a user clicks on a pin the color changes so it is obvious what pin is selected. Thanks for the review.

**Review by mihail-varbanov — CHANGES_REQUESTED** [review]
@manav2modi, I think there are major problems in your last commit [Add color pin feature](https://github.com/rokwire/illinois-app/commit/47af14b44bb1d272c6cc2fb103e3592202f8267c).

1. The purpose of _selectedMapExplore is to drive the content of MapExploreBar. You should not try to handle the specific Stored Sites features in map explore selection mechanism, they should be handled separately and independently. In short, you should leave the existing selection management in ExploreMapPanel untouched, or only disable it in case of Stored Sites map type selection. 

2. I would like to see the design of what you are doing. For me the current map management for stored sites is confusing, inconsistent and not well thought. I do not know if this is your own design decisions, or this behavior was requested explicitly by the University.

**Comment by mihail-varbanov** [comment]
@manav2modi, in addition to above:

3. My belief is that what you did in this branch is conceptually wrong. If your remember, when you started this feature I told you that filtering on stored sites should be performed in ExploreMapPanel, not in ExploreStoriedSightsBottomSheet, and the filtered places content should be passed to ExploreStoriedSightsBottomSheet for displaying. I also suggested selecting filters to get transferred from ExploreStoriedSightsBottomSheet to ExploreMapPanel via Storage service, but this is not the only possible way, of course. The answer that I got from you (as long as remember) was something like that the filtering should be performed only in ExploreStoriedSightsBottomSheet locally, and the filtered places content in ExploreStoriedSightsBottomSheet would not affect ExploreMapPanel display and selection in any way. What happens in this branch is that ExploreStoriedSightsBottomSheet attempts to control the content and selection in ExploreMapPanel, that is wrong. The direction should be the opposite: ExploreMapPanel should maintain its content and selection, ExploreStoriedSightsBottomSheet can only notify ExploreMapPanel about user activity that requires updating that content or selection.

**Comment by manav2modi** [comment]
@mihail-varbanov Thanks for the review. I have tried to separate out the functionality as to not mess with the explore map features as much and created a new variable to keep track of the selected pin. Hopefully this makes it cleaner and less likely to cause any problems. I have also gone ahead and added storiedSites to the analytics list as well. Thanks!

**Review by mihail-varbanov — APPROVED** [review]
The only reason I'm approving this pull request is management's strong desire to release a 6.0 hotfix. I continue to maintain that there are conceptual issues here that should be worked out in calmer times.

**Pull request merged**
